# Generated by Django 3.2.9 on 2022-03-19 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20220318_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditorcompany',
            name='employers',
        ),
        migrations.RemoveField(
            model_name='auditorcompany',
            name='name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
        migrations.AddField(
            model_name='auditorcompany',
            name='auditor_company_activities',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Виды деятельности'),
        ),
        migrations.AddField(
            model_name='auditorcompany',
            name='auditor_company_licence_registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата свидетельства о государственной регистрации'),
        ),
        migrations.AddField(
            model_name='auditorcompany',
            name='auditor_company_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адресс'),
        ),
        migrations.AddField(
            model_name='auditorcompany',
            name='auditor_company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='auditorcompany',
            name='auditor_company_organization_form',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Организационно-правовая форма'),
        ),
        migrations.AddField(
            model_name='auditorcompany',
            name='auditor_company_registration_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер свидетельства о государственной регистрации'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_licence_licenceOrganisation',
            field=models.DateField(blank=True, null=True, verbose_name='Орган предоставивший лицензию'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_licence_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер лицензии'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_licence_registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата предоставлении лицензии'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адресс'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата свидетельства о государственной регистрации'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_registration_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер свидетельства о государственной регистрации'),
        ),
        migrations.AlterField(
            model_name='document',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Документ компании'),
        ),
        migrations.AlterField(
            model_name='document',
            name='link',
            field=models.CharField(max_length=200, verbose_name='Ссылка на файл в хранилище'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование документа'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_user', models.BooleanField(default=False, verbose_name='Пользователь')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Работник')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Руководитель')),
                ('user_first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя')),
                ('user_surname', models.CharField(blank=True, max_length=200, null=True, verbose_name='Фамилия')),
                ('user_second_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Отчество')),
                ('is_company', models.BooleanField(default=False, verbose_name='Компания')),
                ('is_auditor_company', models.BooleanField(default=False, verbose_name='Аудиторская компания')),
                ('auditor_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.auditorcompany', verbose_name='Связанная аудиторская компания')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Связанная компания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='employerdocument',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
