# Generated by Django 3.2.9 on 2022-03-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220319_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_licence_licenceOrganisation',
            field=models.DateField(blank=True, null=True, verbose_name='R'),
        ),
    ]
