# Generated by Django 3.2.9 on 2022-03-19 17:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220319_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorcompany',
            name='auditor_company_licence_registration_date',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 3, 19, 17, 41, 0, 718956, tzinfo=utc), max_length=200, null=True, verbose_name='Дата свидетельства о государственной регистрации'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_licence_licenceOrganisation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Орган выдавший лицензию'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_licence_registration_date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дата предоставлении лицензии'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_registration_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 3, 19, 17, 41, 0, 718556, tzinfo=utc), null=True, verbose_name='Дата свидетельства о государственной регистрации'),
        ),
    ]
