# Generated by Django 3.0 on 2022-03-21 07:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220319_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditorcompany',
            name='auditor_company_activities',
        ),
        migrations.RemoveField(
            model_name='auditorcompany',
            name='auditor_company_organization_form',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_licence_licenceOrganisation',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_licence_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_registration_date',
        ),
        migrations.AddField(
            model_name='auditorcompany',
            name='auditor_company_licence_licenceOrganisation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Орган выдавший лицензию'),
        ),
        migrations.AddField(
            model_name='auditorcompany',
            name='auditor_company_licence_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер лицензии'),
        ),
        migrations.AddField(
            model_name='auditorcompany',
            name='auditor_company_registration_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 3, 21, 7, 45, 57, 232437, tzinfo=utc), null=True, verbose_name='Дата свидетельства о государственной регистрации'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_activities',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Виды деятельности'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_organization_form',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Организационно-правовая форма'),
        ),
        migrations.AlterField(
            model_name='auditorcompany',
            name='auditor_company_licence_registration_date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дата предоставлении лицензии'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_licence_registration_date',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 3, 21, 7, 45, 57, 232102, tzinfo=utc), max_length=200, null=True, verbose_name='Дата свидетельства о государственной регистрации'),
        ),
    ]
