# Generated by Django 3.0 on 2022-03-21 09:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220321_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorcompany',
            name='auditor_company_registration_date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дата свидетельства о государственной регистрации'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_licence_registration_date',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 3, 21, 9, 3, 18, 561379, tzinfo=utc), max_length=200, null=True, verbose_name='Дата свидетельства о государственной регистрации'),
        ),
    ]
