# Generated by Django 3.0 on 2022-03-21 16:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220321_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=200, null=True, verbose_name='Фамилия')),
                ('second_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Отчество')),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_staff',
            new_name='is_employer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_second_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_surname',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_licence_registration_date',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 3, 21, 16, 41, 45, 278670, tzinfo=utc), max_length=200, null=True, verbose_name='Дата свидетельства о государственной регистрации'),
        ),
        migrations.AddField(
            model_name='profile',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Employer', verbose_name='Связанный работник'),
        ),
    ]
