# Generated by Django 3.0 on 2022-03-21 16:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20220321_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorcompany',
            name='auditor_company_clients_companies',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Company', verbose_name='Клиенты аудиторской компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_licence_registration_date',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 3, 21, 16, 51, 43, 525090, tzinfo=utc), max_length=200, null=True, verbose_name='Дата свидетельства о государственной регистрации'),
        ),
    ]
