# Generated by Django 3.0 on 2022-03-21 17:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20220321_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=200, null=True, verbose_name='Статус документа')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='comment',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Замечания'),
        ),
        migrations.AddField(
            model_name='document',
            name='last_edit_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Employer', verbose_name='Кто вносил последнии правки'),
        ),
        migrations.AddField(
            model_name='document',
            name='last_edit_date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Последняя дата изменения'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_licence_registration_date',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 3, 21, 17, 5, 53, 326890, tzinfo=utc), max_length=200, null=True, verbose_name='Дата свидетельства о государственной регистрации'),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.DocumentStatus', verbose_name='Статус документа'),
            preserve_default=False,
        ),
    ]
