# Generated by Django 3.0 on 2022-03-23 07:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20220321_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_licence_registration_date',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 3, 23, 7, 38, 58, 550937, tzinfo=utc), max_length=200, null=True, verbose_name='Дата свидетельства о государственной регистрации'),
        ),
    ]
