# Generated by Django 3.0 on 2022-03-23 18:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20220323_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_licence_registration_date',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 3, 23, 18, 6, 38, 405386, tzinfo=utc), max_length=200, null=True, verbose_name='Дата свидетельства о государственной регистрации'),
        ),
        migrations.AlterField(
            model_name='document',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на файл в хранилище'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.DocumentStatus', verbose_name='Статус документа'),
        ),
    ]
