# Generated by Django 3.0 on 2022-03-24 06:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20220323_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_licence_registration_date',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 3, 24, 6, 0, 52, 918706, tzinfo=utc), max_length=200, null=True, verbose_name='Дата свидетельства о государственной регистрации'),
        ),
        migrations.CreateModel(
            name='Invites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.AuditorCompany')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Company')),
            ],
        ),
    ]
